
version: '3.3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  # a service to generate pa11y results
  # docker-compose run --rm pa11y
  dashboard:
    build: .
    container_name: pa11y
    #command: bash -c "cd /code/pa11y && pa11y-ci --config /code/pa11y/config.json --json > report.json"
    ports:
      - 8080:4000